### ISSUE TITLE
Remove patch from Cargo.toml

### ISSUE THREAD

**Issue by pentamassiv** [ids1024/reis#2]
It looks like your [PR](https://github.com/bytecodealliance/rustix/pull/676) was merged so the vanilla upstream version of rustix can be used instead of a patched version.

```
[patch.crates-io]
# TODO remove when merged
rustix = { git = "https://github.com/ids1024/rustix", branch = "fix-panic" }
```

Thank you for writing this crate. I'll probably use it in the future

**Comment by ids1024** [comment]
Updated to Rustix 0.38: https://github.com/ids1024/reis/commit/7e4b24ddac5db1bf7fdc67835608e858d579e6d5.

Currently the crate is fairly incomplete, subject to change, and only offers a very low level API. My priority here is to have the basics required on the compositor side to add initial EI support to Smithay, then figure out useful Rust abstractions from there.

**Comment by pentamassiv** [comment]
Awesome, thank you :+1: 

No worries, I understand that it will change.
