### ISSUE TITLE
How to run the `type-text` example?

### ISSUE THREAD

**Issue by pentamassiv** [ids1024/reis#3]
I would like to run the `type-text` example but it do not work. I always get a panic

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', examples/type-text.rs:208:58
```

What is needed for it to succeed? I am running Arch with mutter 45.1-1 which should come with EI support. I would have expected that `type-text` would simulate input and type something (`"Hello world!"` if I understand the code correctly). Is it some environment flag that needs to be set? If so, what does it need to be set to? I see that a number of env vars are set in the CI, but setting them to the same values did not help. LIBEI_SOCKET is not set on my machine.

**Comment by feschber** [comment]
The example won't work because mutter does not expose the libel socket directly through the filesystem. You instead need to connect to it through the remote desktop portal.

I may add a PR to update the example or add a helper function for connecting through the portal.

**Comment by ids1024** [comment]
Good point. The `ashpd` crate can be used to call the portal and get an fd.

It would be good to show that in the example.

**Comment by ids1024** [comment]
The example now uses the portal if it doesn't find an ei socket, and now works correctly on Gnome.
